export const courses = [{ name: "MTH 104  Fundamentals of Algebra and Trigonometry. (2 h)" },
			{ name: "MTH 105  Fundamentals of Algebra and Trigonometry. (1 h)" },
			{ name: "MTH 105  Fundamentals of Algebra and Trigonometry. (3 h)" },
			{ name: "MTH 105L  Precalculus Assessment Lab. (1 h)" },
			{ name: "MTH 106  Calculus Foundations. (3 h)" },
			{ name: "MTH 107  Explorations in Mathematics. (3 h)" },
			{ name: "MTH 111  Calculus with Analytic Geometry I. (4 h)" },
			{ name: "MTH 112  Calculus with Analytic Geometry II. (4 h)" },
			{ name: "MTH 113  Multivariable Calculus. (4 h)" },
			{ name: "MTH 117  Discrete Mathematics. (4 h)" },
			{ name: "MTH 121  Linear Algebra I. (3 h)" },
			{ name: "MTH 165  Problem-Solving Seminar. (1 h)" },
			{ name: "MTH 172  Mathematics and Social Justice. (1.5 h)" },
			{ name: "MTH 191  Research Exploration in Mathematics. (3 h)" },
			{ name: "MTH 205  Introduction to Linear Algebra and Differential Equations. (3 h)" },
			{ name: "MTH 214  Multivariable Analysis. (3 h)" },
			{ name: "MTH 215  Axiomatic Systems. (3 h)" },
			{ name: "MTH 225  Linear Algebra II. (3 h)" },
			{ name: "MTH 243  Codes and Cryptography. (3 h)" },
			{ name: "MTH 251  Ordinary Differential Equations. " },
			{ name: "MTH 253  Operations Research. (3 h)" },
			{ name: "MTH 254  Optimization Theory. (3 h)" },
			{ name: "MTH 283  Topics in Mathematics. (3 h)" },
			{ name: "MTH 306  Advanced Mathematics for the Physical Sciences. (3 h)" },
			{ name: "MTH 311  Introductory Real Analysis I. (3 h)" },
			{ name: "MTH 312  Introductory Real Analysis II. " },
			{ name: "MTH 317  Complex Analysis I. (3 h)" },
			{ name: "MTH 321  Modern Algebra I. (3 h)" },
			{ name: "MTH 322  Modern Algebra II. (3 h)" },
			{ name: "MTH 324  Advanced Linear Algebra. (3 h)" },
			{ name: "MTH 326  Numerical Linear Algebra. (3 h)" },
			{ name: "MTH 331  Geometry. (3 h)" },
			{ name: "MTH 333  Introductory Topology. (3 h)" },
			{ name: "MTH 334  Differential Geometry. (3 h)" },
			{ name: "MTH 345  Elementary Number Theory. (3 h)" },
			{ name: "MTH 346  Modern Number Theory. (3 h)" },
			{ name: "MTH 347  Graph Theory. (3 h)" },
			{ name: "MTH 348  Combinatorial Analysis I. (3 h)" },
			{ name: "MTH 349  Combinatorial Analysis II. (3 h)" },
			{ name: "MTH 351  Introduction to Mathematical Modeling. (3 h)" },
			{ name: "MTH 352  Partial Differential Equations. (3 h)" },
			{ name: "MTH 353  Probability Models. (3 h)" },
			{ name: "MTH 354  Discrete Dynamical Systems. (3 h)" },
			{ name: "MTH 355  Introduction to Numerical Methods. (3 h)" },
			{ name: "MTH 357  Probability. (3 h)" },
			{ name: "MTH 372  Math, Statistics, and Society. (3 h)" },
			{ name: "MTH 381  Individual Study. (3 h)" },
			{ name: "MTH 383  Advanced Topics in Mathematics. (3 h)" },
			{ name: "MTH 391  Senior Seminar Preparation. (3 h)" },
			{ name: "MTH 392  Senior Seminar Presentation. (3 h)" },
			{ name: "HES 100  Healthy Lifestyles. (1.5 h)" },
			{ name: "CSC 111  Introduction to Computer Science (4 h)" },
			{ name: "Science I. (3 h)" },
			{ name: "Science II. (3 h)" },
			{ name: "STA 111. (4 h)" },
			{ name: "STA 112. (4 h)" },
			{ name: "STA 310  Probability. (3 h)" },
			{ name: "STA 300  Stats Elective. (3 h)" },
			{ name: "MTH 300  Numerical Elective. (3 h)" },
			{ name: "MTH 100+ Elective. (3 h)" },
			{ name: "MTH 200+ Elective. (3 h)" },
			{ name: "MTH 300+ Elective. (3 h)" }
]
